# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FiNote' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FiNote
	pod 'Eureka', :git => 'https://github.com/xmartlabs/Eureka.git', :branch => 'feature/Xcode9-Swift3_2'
	pod 'SwiftyJSON'
	pod 'Alamofire', '~> 4.5'
	pod 'KeychainAccess'
	pod 'TinyConstraints', :git => 'https://github.com/roberthein/TinyConstraints.git', :branch => 'Release_2.1.2'
	pod 'Floaty', '~> 3.0.0'
	pod 'PopupDialog', '0.5.4'
	pod 'NVActivityIndicatorView', '3.7.0'

end
