# Uncomment the next line to define a global platform for your project
platform :ios, '11.2'

target 'FiNote' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FiNote

pod 'UPCarouselFlowLayout'
pod 'KeychainAccess'
pod 'SwiftyJSON'
pod 'Alamofire'
pod 'Eureka'
pod 'TinyConstraints'
pod 'PopupDialog'
pod 'NVActivityIndicatorView'
pod 'AlamofireImage'
pod 'StatusProvider'
pod 'PromiseKit'
#pod 'Floaty', '~> 4.0.0'
pod 'Floaty'
end
