# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-11 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FiNote_API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie_onomatopoeia',
            old_name='movie_id',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='movie_onomatopoeia',
            old_name='onomatopoeia_id',
            new_name='onomatopoeia',
        ),
        migrations.RenameField(
            model_name='movie_user',
            old_name='movie_id',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='movie_user',
            old_name='user_id',
            new_name='user',
        ),
    ]
