# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-09 00:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FiNote_API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='is_dummy',
        ),
    ]
