# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FiNote_API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='birthday',
            field=models.IntegerField(default=1900),
        ),
        migrations.AddField(
            model_name='authuser',
            name='sex',
            field=models.CharField(default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='email',
            field=models.EmailField(default='email', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='username',
            field=models.CharField(default='username', max_length=30, unique=True),
        ),
    ]
