# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-15 03:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FiNote_API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_user_onomatopoeia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
