# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-09 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FiNote_API', '0002_remove_authuser_is_dummy'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='is_dummy',
            field=models.BooleanField(default=False),
        ),
    ]
