# Generated by Django 2.0.1 on 2018-02-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FiNote_API', '0002_auto_20180128_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='birthyear',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
