# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-11 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FiNote_API', '0002_auto_20180111_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
