# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 17:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FiNote_API', '0003_genre_genre_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FiNote_API.Movie')),
                ('onomatopoeia', models.ManyToManyField(to='FiNote_API.Onomatopoeia')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
