# Generated by Django 2.0.1 on 2018-01-21 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FiNote_API', '0003_remove_authuser_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authuser',
            old_name='birthday',
            new_name='birthyear',
        ),
    ]
