# Generated by Django 2.0.1 on 2018-02-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FiNote_API', '0003_auto_20180202_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='birthyear',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
