# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-11 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FiNote_API', '0003_movie_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_user',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
