# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-11 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FiNote_API', '0003_authuser_is_dummy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='sex',
        ),
        migrations.AlterField(
            model_name='backup',
            name='add_day',
            field=models.IntegerField(default=11),
        ),
    ]
