# Generated by Django 2.0.4 on 2018-04-29 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FiNote_API', '0004_auto_20180202_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='releate_date',
            field=models.DateField(null=True),
        ),
    ]
