# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-11 23:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FiNote_API', '0004_auto_20180111_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='DVDFAV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dvd', models.IntegerField(default=0)),
                ('fav', models.IntegerField(default=0)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FiNote_API.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='backup',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='backup',
            name='onomatopoeia',
        ),
        migrations.RemoveField(
            model_name='backup',
            name='username',
        ),
        migrations.DeleteModel(
            name='BackUp',
        ),
    ]
