# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-11 01:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FiNote_API', '0004_auto_20180111_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backup',
            name='add_day',
        ),
        migrations.RemoveField(
            model_name='backup',
            name='add_month',
        ),
        migrations.RemoveField(
            model_name='backup',
            name='add_year',
        ),
        migrations.AddField(
            model_name='backup',
            name='add_date',
            field=models.DateField(default=datetime.date(2018, 1, 11)),
        ),
    ]
