# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-11 03:59
from __future__ import unicode_literals

import FiNote_API.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FiNote_API', '0005_auto_20180111_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='img',
            field=models.FileField(blank=True, upload_to=FiNote_API.models.AuthUser.get_img_name),
        ),
    ]
