# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-11 23:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FiNote_API', '0005_auto_20180111_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvdfav',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
