# Generated by Django 2.0.4 on 2018-04-29 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FiNote_API', '0005_movie_releate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='releate_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
