# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FiNote_API', '0005_auto_20170425_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='dvd',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='backup',
            name='fav',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='overview',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
