# Generated by Django 2.0.4 on 2018-04-29 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FiNote_API', '0006_auto_20180429_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='releate_date',
            new_name='release_date',
        ),
    ]
