# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-12 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FiNote_API', '0007_auto_20180112_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvdfav',
            name='dvd',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dvdfav',
            name='fav',
            field=models.BooleanField(default=False),
        ),
    ]
