# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-12 21:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FiNote_API', '0008_auto_20180112_0116'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieUserOnomatopoeia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FiNote_API.Movie')),
                ('onomatopoeia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FiNote_API.Onomatopoeia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
