# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FiNote_API', '0008_auto_20170429_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='img',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='backup',
            name='add_day',
            field=models.IntegerField(default=13),
        ),
        migrations.AlterField(
            model_name='backup',
            name='add_month',
            field=models.IntegerField(default=5),
        ),
    ]
