# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FiNote_API', '0009_auto_20170513_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='img',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='backup',
            name='add_day',
            field=models.IntegerField(default=14),
        ),
    ]
