# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-12 23:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FiNote_API', '0010_auto_20180112_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dvdfav',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='dvdfav',
            name='user',
        ),
        migrations.AddField(
            model_name='dvdfav',
            name='movie_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='FiNote_API.Movie_User'),
        ),
    ]
