# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FiNote_API', '0012_auto_20170526_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(to='FiNote_API.Genre'),
        ),
    ]
