# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FiNote_API', '0013_auto_20170526_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='backup',
            name='add_day',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='backup',
            name='add_month',
            field=models.IntegerField(default=6),
        ),
    ]
