from rest_framework import routers
from .views import *

router = routers.DefaultRouter()
router.register(r'signup', SignUpViewSet, 'signup')
router.register(r'signinwithtoken', SignInWithTokenViewSet, 'signinwithtoken')
router.register(r'signinnotoken', SignInNoTokenViewSet, 'signinnotoken')
router.register(r'changepassword', ChangePasswordViewSet, 'changepassword')
router.register(r'changeemail', ChangeEmailViewSet, 'changeemail')
router.register(r'changesex', ChangeSexViewSet, 'changesex')
router.register(r'setprofileimg', SetProfileImgViewSet, 'setprofileimg')
router.register(r'movieadd', MovieAddViewSet, 'movieadd')
router.register(r'onomatopoeiaupdate', OnomatopoeiaUpdateViewSet, 'onomatopoeiaupdate')
router.register(r'statusupdate', StatusUpdateViewSet, 'statusupdate')
router.register(r'deletebackup', DeleteBackupViewSet, 'deletebackup')
router.register(r'users', UserViewSet, 'users')
router.register(r'genres', GenreViewSet, 'genres')
router.register(r'onomatopoeia', OnomatopoeiaViewSet, 'onomatopoeia')
router.register(r'movies', MovieViewSet, 'movies')
router.register(r'onomatopoeia_counts', OnomatopoeiaCountViewSet, 'onomatopoeia_counts')
